version: '3.8'

services:
  akto-api-security-testing:
    image: aktosecurity/mini-testing:a-1705-merge
    environment:
      RUNTIME_MODE: hybrid
      DATABASE_ABSTRACTOR_SERVICE_TOKEN: 
      PUPPETEER_REPLAY_SERVICE_URL: "http://akto-api-security-puppeteer-replay:3000"
    restart: always

  akto-api-security-puppeteer-replay:
    image: public.ecr.aws/aktosecurity/akto-puppeteer-replay:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: always