name: Push Release Notes to Beamer and Discord

on:
  workflow_dispatch

jobs:
  push-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bolt
        uses: koalalab-inc/bolt@v1
      - name: Get Latest Release
        id: get_latest_release
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install requests
          python3 - <<EOF
          import os
          import requests
          
          github_token = os.getenv('GITHUB_TOKEN')
          repo_owner = 'akto-api-security'
          repo_name = 'akto'
          headers = {'Authorization': f'Bearer {github_token}'}
          url = f'https://api.github.com/repos/{repo_owner}/{repo_name}/releases/latest'
          response = requests.get(url, headers=headers)
          data = response.json()

          tag_name = data.get('tag_name')
          description = data.get('body')
          description_lines = description.split('\n') if description else []
          description_lines = [line.strip() for line in description_lines if line.strip()]

          release_notes = '<ul>'
          if description_lines:
              first_line = description_lines[0].lstrip('#').strip()
              release_notes += f'<h3>{first_line}</h3>'
              for line in description_lines[1:-1]:  # Exclude the last line
                  if 'by' in line:
                      line = line.split('by', 1)[0].strip()
                  release_notes += f'<li>{line[1:]}</li>'
          release_notes += '</ul>'
          release_notes2 = '<p></p>Have questions? Ask on <a href=https://discord.com/invite/Wpc6xVME4s >Discord</a> or our <a href=https://community.akto.io >Community page</a>'
          release_notes = release_notes+release_notes2
      
          
          print(f"::set-output name=tag_name::{tag_name}")
          print(f"::set-output name=release_notes::{release_notes}")
          EOF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Tag Name and Description
        run: |
          echo "Tag Name: ${{ steps.get_latest_release.outputs.tag_name }}"
          echo "Description: ${{ steps.get_latest_release.outputs.release_notes }}"

      - name: Push Release Notes to Beamer
        env:
          BEAMER_API_TOKEN: ${{ secrets.BEAMER_API_KEY }}
          RELEASE_TAG: ${{ steps.get_latest_release.outputs.tag_name }}
          RELEASE_NOTES: ${{ steps.get_latest_release.outputs.release_notes}}
        run: |
          # Push release notes to Beamer
          curl --request POST \
            --url https://api.getbeamer.com/v0/posts \
            --header "Content-Type: application/json" \
            --header "Beamer-Api-Key: $BEAMER_API_TOKEN" \
            --data "{
              \"title\": [ \"Release $RELEASE_TAG\" ],
              \"content\": [ \"$RELEASE_NOTES\" ],
              \"category\": \"new\",
              \"publish\": true
            }"
            
